/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/film.glb 
Author: Alligator Alex (https://sketchfab.com/alligator_alex)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/35mm-film-roll-6d8a6d290de043e898420a04072a3a1e
Title: 35mm Film Roll
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import gsap from 'gsap';

export function Film(props) {
  const { nodes, materials } = useGLTF('/film.glb');
  const film = useRef();
  const scroll = useScroll();
  const tl = useRef();  


  useFrame((state, delta) =>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })
  
  useLayoutEffect(() =>{
    tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})
  
    tl.current
      .to(film.current.rotation, {y: -1}, 2)
      .to(film.current.position, {x: 1}, 2)
  
      .to(film.current.rotation, {y: 1}, 6)   
      .to(film.current.position, {x: -1}, 6)
  
      .to(film.current.rotation, {y: 0}, 11)
      .to(film.current.rotation, {x: 1}, 11)
      .to(film.current.position, {x: 0}, 11)
  
      .to(film.current.rotation, {y: 0}, 13)
      .to(film.current.rotation, {x: -1}, 13)    
      .to(film.current.position, {x: 0}, 13)
  
      .to(film.current.rotation, {y: 0}, 16)   
      .to(film.current.rotation, {x: 0}, 16) 
      .to(film.current.position, {x: 0}, 16)    
  
      .to(film.current.rotation, {y: 0}, 20)   
      .to(film.current.rotation, {x: 0}, 20) 
      .to(film.current.position, {x: 0}, 20)   
  
  },[])
  return (
    <group {...props} dispose={null} ref = {film}>
      <group scale={0.01}>
        <mesh geometry={nodes['LP_roll_film_Material_#27_0'].geometry} material={materials.Material_27} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/film.glb')
